### ISSUE TITLE
Article: n-gram

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#108]

**Comment by ktrnka** [comment]
For this article, do we just want to define n-grams and link to the language model article for n-gram models?

**Comment by cefoo** [comment]
Hi @ktrnka!

Yeah, a definition and links is great.
Perhaps we can also mention [statistical machine translation](https://machinetranslate.org/statistical-machine-translation) and [language model](https://machinetranslate.org/language-model#n-gram-maximum-likelihood-estimate), as the concept is mentioned in those articles.
