### ISSUE TITLE
404 for www (www.machinetranslate.org)

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#137]
This weekend we moved from Gitbook to Github Pages with Just the Docs.

Despite adding a CNAME to point www (www.machinetranslate.org) to @ (machinetranslate.org), it's still going to Gitbook (after more than 24 hours).  After deleting the Gitbook site completely, now it's going to the Gitbook 404 page.

The problem seems to be that both Machine Translate and Gitbook use Cloudflare for DNS, and Cloudflare lets partners like Gitbook route domains that it claims are from its users.

https://community.cloudflare.com/t/dns-subdomain-no-longer-works-nor-redirects-to-anything/240984

I've contacted Gitbook, like he did.

**Comment by bittlingmayer** [comment]
Looks to be fixed, probably due to Cloudfare DNS refreshing, not any Gitbook support

**Comment by bittlingmayer** [comment]
Similar issue: https://community.cloudflare.com/t/dns-orange-cloudflare-cloud-pointing-to-wrong-record/305894/6

**Comment by bittlingmayer** [comment]
https://community.cloudflare.com/t/subdomain-traffic-still-being-routed-to-old-cname-aliased-domain-instead-of-new-a-record/254426/5

**Comment by zouharvi** [comment]
Still doesn't seem to be routing correctly. Is it possible for the refresh to take that long?

Points to the same IP.

```
$ dig www.machinetranslate.org
www.machinetranslate.org. 183	IN	A	172.67.147.179
www.machinetranslate.org. 183	IN	A	104.21.95.200

$ dig machinetranslate.org
machinetranslate.org.	120	IN	A	104.21.95.200
machinetranslate.org.	120	IN	A	172.67.147.179
```

**Comment by bittlingmayer** [comment]
Now it's a 526 Error with HTTPS, so I changed SSL  from *Full (strict)* to *Full* per https://support.cloudflare.com/hc/en-us/articles/115003011431#526error.

**Comment by zouharvi** [comment]
Works now.

**Comment by bittlingmayer** [comment]
It's still 404ing on trailing slash, otherwise good.
