### ISSUE TITLE
Article: Locale

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#172]

**Comment by ktrnka** [comment]
What scope did you have in mind for this? Did you mean regional language variants like enUS vs enUK and the associated naming standards?

**Comment by cefoo** [comment]
Hi @ktrnka!

Yeah, we mean language variants.
We would like to help our audience know that some MT providers offer locale-specific languages, while others offer generic languages, and what that means.
If the info is available, we have already added the appropriate locales when an MT system supports it (see [Alexa AI](https://machinetranslate.org/alexa-ai)). Do you think it would be interesting to auto-generate a list or something similar to that when talking about `locales`?
