### ISSUE TITLE
Feature: Citation listing (bibtex)

### ISSUE THREAD

**Issue by zouharvi** [machinetranslate/machinetranslate.org#204]
If someone wants to cite machinetranslate, what should the citation be?

One solution to this would be to include a bibtex citation entry somewhere on the about page.

**Comment by bittlingmayer** [comment]
Can you share more about the use case?

I guess he or she would want to cite a specific page AND version, no?  (e.g. in Wikipedia they usually use Wayback Machine links because pages go out of date or change and then the "fact" is no longer there.)

We could generate it at the bottom of every page.

**Comment by zouharvi** [comment]
The usecase: I want to write a paper about popularization of MT and I want to mention Machinetranslate.

Options:
1. I simply link to machinetranslate in the footnotes. This is easy & convenient but does not really adhere to the academic rules of citation because technically we are not attributing the citation to the authors. Also it will break should the link change in 5 years.
2. Generate a bibtex (see the bottom of this [blogpost of one of my excolleague's](https://jlibovicky.github.io//2022/01/20/MT-Weekly-Evil-Multilingual-Models.html)). I can simply copy&paste this to my latex bibliography and cite it properly.

I would suggest not adding this to every page as that creates extra clutter & information and as you said, the organization may change. But for now, having at least one such box in the about page that cites the whole project would be beneficial, at least for me.

**Comment by zouharvi** [comment]
Coming back to this, I think that having this at every footer is definitely too much and is not useful for 99% of the visitors. However, there should be a canonical way listed how to cite machinetranslate. Maybe this could be included in the *about* section? (If this is the right way to cite this project.) 

```
@misc{machinetranslate,
  title = {{M}achinetranslate.org},
  howpublished = {\url{https://machinetranslate.org/}},
  note = {Accessed: 2022-05-12}
}
```

Ideally it would also list all the authors (`author = {Adam, Cecilia, etc..},`) which would definitely incetivize academics to contribute more, though I don't know how viable and desired this is. :slightly_smiling_face:

**Comment by bittlingmayer** [comment]
Sounds good.

Note that the name is *Machine Translate*.
