### ISSUE TITLE
Article: MT support in CAT/TMS

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#211]
**Article title:** MT integrations in CAT/TMS

**Directory:** Resources

**Description**: Machine translation integrations and possibilities in CAT/TMX systems

**Definition**:
What CAT/TMS support MT?
What MT systems are supported?
Is the MT connection added by default in the configuration or do you need to access via a plugin?
How do they deal with customisation?
etc.

**Comment by bittlingmayer** [comment]
We don't necessarily want to auto-generate *pages*.

For example, we can make a `_layouts/language.html`

And then `languages/russian.md` will be:

```
code: ru
---

**Russian** was one of the first languages for which machine translation was researched and developed, and remains one of the best supported languages.

...

```
