### ISSUE TITLE
Bug: Link text overflows the Featured article box (phone)

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#217]
**Description:** The link text overflows the Featured article box in the phone browser.

**Steps to reproduce the behavior:**
1. In your phone, open the browser
2. Go to machinetranslate.org
3. Scroll down to 'Featured article'
5. See error

**Expected behavior:** There should be a line break for the text to be contained inside the 'Featured article' box.

**Screenshots [optional]:**
![overflow](https://user-images.githubusercontent.com/33723604/157033965-2021b542-8f89-428d-9363-05afe9129214.JPG)

**Device:**
 - OS: iOS 15.3.1
 - Browser: Safari
 - Version: 15

**Comment by luismond** [comment]
I think this can be solved with a change in the CSS. The attribute  `white-space` for links of the class `main-content` is set to `nowrap`. If this is changed to `normal`, the line would be displayed correctly.
