### ISSUE TITLE
Add Machine Translate to the European Language Grid

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#235]
https://european-language-grid.readthedocs.io/en/stable/

I suppose it's an Organisation, not a Project.

https://european-language-grid.readthedocs.io/en/stable/all/3_Contributing/Organisation.html

**Comment by cefoo** [comment]
This has been submitted and is currently under evaluation by ELG.

**Comment by cefoo** [comment]
[live.european-language-grid.eu/catalogue/organization/18853](https://live.european-language-grid.eu/catalogue/organization/18853)
