### ISSUE TITLE
Update translation / localization

### ISSUE THREAD

**Issue by zouharvi** [machinetranslate/machinetranslate.org#318]
There's already an article on [Translation and localization](https://machinetranslate.org/translation-and-localisation), however it does not explain what actually is the difference between translation and localization.

As a computer scientists, my vague understanding is that localization has to do something with the culture and common idioms as well but that's it. Having an explanation on this disambiguation (together with examples) would be helpful to me and others in my position.

**Comment by zouharvi** [comment]
@martab0

**Comment by cefoo** [comment]
This is a great idea!
In the future, we should add notes to other articles as well for both localization and research sectors to fully understand each other's concepts, ie `string` and `segment`, `back-translation` and `round-trip translation`, etc.
