### ISSUE TITLE
Update engines:languages

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#319]
- TextShuttle launched Romansh (`rm`)
- We're missing NeuralSpace, we should add them or ask them to add themselves.
- We contact all the other APIs to ask them to check their information.

**Comment by cefoo** [comment]
- We currently just list the languages offered by TextShuttle through their basic plan and API and RestFul API.  However, they told me that they will update this file as soon as the new TextShuttle website is available.
I'm not sure if Romanesh is a part of their API yet.
[Source](https://www.textshuttle.ai/product/features)
- I've updated the Lingmo info. They updated their website recently.

**Comment by bittlingmayer** [comment]
We should also add the `custom_languages` for a few, like Amazon, so we can use `custom_languages` in the pages.
