### ISSUE TITLE
Article: Predictive MT

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#333]
**Article title:** *Predictive MT*

**Directory:** *Customisation*

**Definition**: Recalculation of the MT as the translator makes changes

**Comment by ktrnka** [comment]
@cefoo This is the same as interactive machine translation, which is an alternative to post-editing, right? If so I can take this one

**Comment by cefoo** [comment]
Hi @ktrnka! Please go ahead with the **interactive machine translation** article.

By *predictive*, I meant the ability of the MT engine to suggest terms as the post-editor types, based on the source input. However, I think we should use the term "interactive", as you mention.

**Comment by ktrnka** [comment]
So I've got a draft but it's tricky to explain predictive text. How would you feel about including an animated gif, such as this one:
![casmacat_imt](https://user-images.githubusercontent.com/2133115/212486256-0d52e5d1-736b-4f65-8a75-f326a6d9b226.gif)

It's from https://www.casmacat.eu/ -- I found it actually from a user study of IMT.

**Comment by bittlingmayer** [comment]
Seems good, just need to add attribution.

We have a few similar examples, maybe @cefoo can point to one.

And maybe we should add a section on images to the style guide?

**Comment by cefoo** [comment]
We have [an instruction about images](https://machinetranslate.org/style#images) in the style guide, but I should add the reference instruction.

As regards how to add an attribution, I can point to these two examples:
1- [ModelFront's Hybrid Translation diagram](https://machinetranslate.org/hybrid-translation#workflow-diagram)
2- [Unbabel's Metrics Evolution slide](https://github.com/machinetranslate/machinetranslate.org/blob/0e4961335f47d5f1a6a077b14e7437d0c2cf1502/quality/metrics/metrics.md#evolution) (not yet merged.)

Hope it helps!
