### ISSUE TITLE
Bug: machinetranslate.org website inaccessible 

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#340]
**Description:** Members of eTranslation have reported that they cannot access [machinetranslate.org](https://machinetranslate.org)

**Steps to reproduce the behavior:**
*This seems to be happening only for eTranslation employees and very few people in Europe*
1. Go to either http://machinetranslate.org or https://machinetranslate.org.
2. The website doesn't load at all.

**Expected behavior:** The website should load as it is live and working for other people.

**OS:** Windows 10
**Browser**: Firefox, Google Chrome

**Comment by bittlingmayer** [comment]
Is this still an issue?

**Comment by cefoo** [comment]
I've contacted them to check.
I'll close it for now, as they are the only ones who reported the issue.
