### ISSUE TITLE
Article: MTrans

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#480]
**Article title:** *MTrans*

**Directory:** apis

**Description**: *The MTrans machine translation API*

MTrans is supported by Crowdin, and apparently mainly for translating to and from Japanese.

https://store.crowdin.com/mtrans

**Comment by cefoo** [comment]
According to the description, it looks like MTrans is an aggregator:

> MTrans for Crowdin is a robust machine translation solution that offers multiple translation engines, customizable glossaries, style replacements, and automatic post-editing to deliver high-quality translations with minimal effort.
