### ISSUE TITLE
Bug: Build time is too long

### ISSUE THREAD

**Issue by tovmasharrison** [machinetranslate/machinetranslate.org#489]
On GitHub CI it is taking [20 minutes](https://github.com/machinetranslate/machinetranslate.org/actions/runs/5294983510/jobs/9584870628), and similarly for me locally (ThinkPad, Ubuntu).

There are some obvious performance bottlenecks, for example in language.html:
```
{% assign language = false %}
{% for lang in site.data.languages %}
  {% if lang.codes.first == page.code %}
    {% assign language = lang %}
  {% endif %}
{% endfor %}
```
So for every language, we're looping over all languages.

In general, we should try to move more out of Liquid layout templates and into generate.py.

**Comment by bittlingmayer** [comment]
Let's leave this open, because it's still needs to get even faster.

Right now it's mainly the render loop.

We could try to parellelize with YJIT - https://talk.jekyllrb.com/t/psa-faster-builds-with-yjit/7853 - but it requires Ruby 3.1.

**Comment by bittlingmayer** [comment]
One more idea to make the build faster:

In generate.py we could generate .html, not .md, and potentially even avoid using any Liquid.

So basically those pages would not even need to go through Jekyll/Liquid rendering, because we'd be rendering ourselves.

Adam

**Comment by bittlingmayer** [comment]
According to https://github.com/just-the-docs/just-the-docs/issues/863, there was a speedup in v0.4.0.

It looks like we have frozen the version of Just The Docs, maybe we should upgrade it?
[_config.yml](https://github.com/machinetranslate/machinetranslate.org/blob/01ea9eeb0b480a9eba9b51d52a85399b234e517c/_config.yml#L165)
```
# Just the Docs
--
165 | remote_theme: pmarsceill/just-the-docs@v0.3.3
166 | logo: favicon.ico
167 | color_scheme: swissred
168 | search:

</div></div></div></div></div></div><br class="Apple-interchange-newline">
```

**Comment by bittlingmayer** [comment]
Another thing to try: https://github.com/benbalter/jekyll-include-cache
