### ISSUE TITLE
Bug: Code in headings is not readable

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#496]
**Description:**
Code (backticks in Markdown / `<code>`...`</code>`) is not visible in headings (`<h1>`...`</h1>` etc), because the color of the text is transparent or the same color as the background.

**Steps to reproduce the behavior:**
1. Go to [*Communities* > *StackOverflow `machine translation`*](https://machinetranslate.org/communities#stackoverflow-machine-translation)

**Expected behavior:**

The full heading should be readable.

**Screenshots [optional]:**

<img width="639" alt="Screenshot 2023-07-26 at 17 34 34" src="https://github.com/machinetranslate/machinetranslate.org/assets/11457984/4d2eefdb-7476-4b3e-bd95-4cf21b519b95">

<img width="1283" alt="Screenshot 2023-07-26 at 17 34 56" src="https://github.com/machinetranslate/machinetranslate.org/assets/11457984/29beda39-f125-436c-90e1-094ed4de1fb7">

<img width="650" alt="Screenshot 2023-07-26 at 17 34 48" src="https://github.com/machinetranslate/machinetranslate.org/assets/11457984/079a52fb-a58e-44c7-bc91-02c9a3090b4e">

**Device:**

 - OS: *e.g. iOS8.1*
 - Browser: Brave
 - Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)

**Additional context:**

The issue is that we added a custom gradient for headings.  It almost seems like some kind of CSS bug.  It is not a JTD issue, as far as I know.

Disabling either `h3` > `-webkit-text-fill-color` or `code` > `background-color` fixes it.

**Comment by harsh3311** [comment]
h1, h2, h3, h4, h5, code {
    background: linear-gradient(45deg, #DA291C, #ed7f78, #DA291C, #71150f);

Only add code to gradient property and its done then

**Comment by bittlingmayer** [comment]
@harsh3311 Thanks!  You are more than welcome to contribute a pull request!

**Comment by devbytemehedi** [comment]
Hey there! 👋
I'm a beginner looking to contribute to open-source projects, and I'm interested in working on this issue.

- **Is it okay for me to start working on this?** 
- **Any specific guidelines I should follow?**

**Comment by bittlingmayer** [comment]
Hi @devbytemehedi 

Yes, though may you could check if @harsh3311 has a draft PR out.

As far as guidelines:
- Have a look at the [README](https://github.com/machinetranslate/machinetranslate.org/blob/master/README.md) for how to run yourself.
- Have a look at [CONTRIBUTING](https://github.com/machinetranslate/machinetranslate.org/blob/master/CONTRIBUTING.md#creating-and-editing-articles)
- Try to adhere to the general style and approach of the file you're editing, like [custom.scss](https://github.com/machinetranslate/machinetranslate.org/blob/master/_sass/custom/custom.scss)
- https://just-the-docs.com/docs/customization/#custom-schemes
