### ISSUE TITLE
Bug: This list in Customisation is broken

### ISSUE THREAD

**Issue by bittlingmayer** [machinetranslate/machinetranslate.org#536]
**Description:** The list is Customisation is missing many APIs.

**Steps to reproduce the behavior:**

Visit https://machinetranslate.org/customisation, then compare to e.g. https://machinetranslate.org/glossaries.

**Expected behavior:**

https://machinetranslate.org/customisation should list the *superset* of the APIs listed in:
- https://machinetranslate.org/adaptive
- https://machinetranslate.org/fine-tuning
- https://machinetranslate.org/formality
- https://machinetranslate.org/glossaries

**Additional context:**

```
{% assign customisable_apis = site.data.apis | where: "customisation_languages", true | where: "glossary", true | concat: site.data.apis | where: "formality", true | concat: site.data.apis | where: "adaptive", true | concat: site.data.apis | where: "fine-tuning", true %}
```
My guess is, it needs to be changed to:

```
{% assign customisable_apis = site.data.apis | where: "customisation_languages", true | concat: site.data.apis | where: "glossary", true | concat: site.data.apis | where: "formality", true | concat: site.data.apis | where: "adaptive", true | concat: site.data.apis | where: "fine-tuning", true %}
```

**Comment by cefoo** [comment]
Related to #485
