### ISSUE TITLE
Feature: Tuvan (Tuvinian) is a Turkic language

### ISSUE THREAD

**Issue by josph0** [machinetranslate/machinetranslate.org#624]
**Problem [optional]:** * “Tuvan is Turkic language, not Mongolic. Also, Tuvan is much more used than Tuvinian. Google also uses Tuvan: https://support.google.com/translate/answer/15139004”*

**Request:** *“Change Mongolic language family to Turkic.”*
*“Change primary name to Tuvan.”*

**Additional context**:

**Comment by cefoo** [comment]
Thank you for the issue!
#[913b7c4](https://github.com/machinetranslate/machinetranslate.org/commit/913b7c4812dea37b87e52ae546f0d9c16ec0d798)
