### ISSUE TITLE
Article: Tokenisation

### ISSUE THREAD

**Issue by cefoo** [machinetranslate/machinetranslate.org#74]

**Comment by ktrnka** [comment]
For this one, I could describe basic tokenization and common approaches in English if that'd help. I don't know the current best practices for non-space-segmented languages but I could make a stub section if that works

**Comment by cefoo** [comment]
Hi @ktrnka! Thanks for your help!

Making stubs is perfect. I'd add a definition and explain the purpose of tokenisation ([UK spelling](https://machinetranslate.org/style#default-to-wikipedia-style)) in machine translation, plus the description of the basic process.
We should focus on the info that is strictly relevant for machine translation.

Do not worry about the current best practices. We aim at having evergreen content. You may notice that we phrase things like "As of 2022, Google Translate supported XXX language pairs" for evergreen purposes.

Two/three paragraphs with 2/3 short sentences, no fillers, just pure content - that would be great!

You can edit [this page](https://machinetranslate.org/tokenisation) which we have already created.
